-- demo_sites: metadata for AI-generated, category-token-driven demo sites.
-- The actual HTML lives in Supabase Storage (bucket: demo-sites); this table
-- points at it. Public (anon) can read only rows with status='ready' — no
-- write access for anon/authenticated, only service-role.
--
-- This is additive and does NOT touch the existing public_demo_sites view,
-- which stays live for the sites already generated by generate-site. This
-- table is used once generate-design-html / publish-demo-site are built.
create table public.demo_sites (
  id                uuid primary key default gen_random_uuid(),
  lead_id           uuid references public.leads(id) on delete cascade,
  demo_slug         text unique not null,
  business_name     text not null,
  city              text,
  state             text,
  business_category text,
  content_json      jsonb,
  storage_path      text,
  status            text not null default 'queued', -- 'queued' | 'generating' | 'ready' | 'failed'
  error             text,
  generated_at      timestamptz,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now()
);

create index idx_demo_sites_lead_id on public.demo_sites(lead_id);
create index idx_demo_sites_demo_slug on public.demo_sites(demo_slug);
create index idx_demo_sites_status on public.demo_sites(status);

alter table public.demo_sites enable row level security;

create policy "public_can_read_ready_demo_sites"
on public.demo_sites for select
to anon, authenticated
using (status = 'ready');
