// BuildItToday.ai — Export generators for the Design Studio
// Produces JSON spec, Markdown design doc, CSS variables, and Tailwind config.

import type { DesignSpec } from "./intake-config";
import {
  colorThemeOptions,
  sectionDefs,
  primitiveGroups,
  radiusRem,
  fontStack,
  borderWidth,
  resolveDarkCanvas,
  resolveType,
  formOptions,
  contentSectionOptions,
} from "./intake-config";
import { themes } from "./themes";

// Map primitive group key -> DesignSpec field name
const primitiveField: Record<string, keyof DesignSpec> = {
  buttons: "buttonStyle",
  inputs: "inputStyle",
  display: "displayStyle",
  feedback: "feedbackStyle",
  navigation: "navStyle",
  overlays: "overlayStyle",
  data: "dataStyle",
};

function getOptionLabel(options: { value: string; label: string }[], value?: string): string {
  if (!value) return "—";
  return options.find((o) => o.value === value)?.label ?? value;
}

export function buildJsonDoc(spec: DesignSpec) {
  const theme = colorThemeOptions.find((t) => t.value === spec.colorTheme);
  const colors = themes[spec.colorTheme].colors;
  const dc = resolveDarkCanvas(spec);
  const type = resolveType(spec);
  return {
    project: "BuildItToday Website Design Specification",
    generatedAt: new Date().toISOString(),
    layer1: {
      colorTheme: theme?.name ?? spec.colorTheme,
      hexColors: colors,
      mode: spec.mode,
      darkCanvas: dc,
      radius: spec.radius,
      radiusRem: radiusRem[spec.radius],
      typography: {
        ...fontStack[spec.font],
        headingWeight: type.headingWeight,
        headingStyle: type.headingStyle,
        bodyWeight: type.bodyWeight,
        letterSpacing: type.letterSpacing,
        headingCase: type.headingCase,
      },
      border: spec.border,
      borderWidth: borderWidth[spec.border],
      shadow: spec.shadow,
    },
    layer2: {
      primitives: Object.fromEntries(
        primitiveGroups.map((g) => [g.key, getOptionLabel(g.options, String(spec[primitiveField[g.key]]))])
      ),
      forms: spec.forms.map((f) => formOptions.find((o) => o.value === f)?.label ?? f),
      contentSections: spec.contentSections.map((s) => contentSectionOptions.find((o) => o.value === s)?.label ?? s),
    },
    layer3: {
      sections: Object.fromEntries(
        sectionDefs.map((s) => [
          s.key,
          { title: s.title, selected: getOptionLabel(s.options, spec.sections[s.key]) },
        ])
      ),
    },
  };
}

export function buildMarkdownDoc(spec: DesignSpec): string {
  const c = themes[spec.colorTheme].colors;
  const colorName = colorThemeOptions.find((t) => t.value === spec.colorTheme)?.name;
  const type = resolveType(spec);
  const lines: string[] = [];
  lines.push("# Website Design Specification");
  lines.push("");
  lines.push("## 1. Global Tokens");
  lines.push("| Token | Value |");
  lines.push("| --- | --- |");
  lines.push(`| Color Theme | ${colorName ?? spec.colorTheme} |`);
  lines.push(`| Background | ${c.light} |`);
  lines.push(`| Dark Surface | ${c.dark} |`);
  lines.push(`| Dark Canvas | ${spec.darkCanvas} |`);
  lines.push(`| Primary / Accent | ${c.primary} |`);
  lines.push(`| Mode | ${spec.mode} |`);
  lines.push(`| Radius | ${spec.radius} |`);
  lines.push(`| Heading Font | ${fontStack[spec.font].heading} |`);
  lines.push(`| Body Font | ${fontStack[spec.font].body} |`);
  lines.push(`| Heading Weight | ${type.headingWeight} |`);
  lines.push(`| Heading Style | ${type.headingStyle} |`);
  lines.push(`| Body Weight | ${type.bodyWeight} |`);
  lines.push(`| Letter Spacing | ${type.letterSpacing} |`);
  lines.push(`| Heading Case | ${type.headingCase} |`);
  lines.push(`| Border | ${spec.border} |`);
  lines.push(`| Shadow | ${spec.shadow} |`);
  lines.push("");
  lines.push("## 2. Shadcn Components");
  for (const g of primitiveGroups) {
    lines.push(`- **${g.title}:** ${getOptionLabel(g.options, String(spec[primitiveField[g.key]]))}`);
  }
  lines.push(`- **Forms Needed:** ${spec.forms.map((f) => formOptions.find((o) => o.value === f)?.label ?? f).join(", ") || "—"}`);
  lines.push(`- **Content Sections:** ${spec.contentSections.map((s) => contentSectionOptions.find((o) => o.value === s)?.label ?? s).join(", ") || "—"}`);
  lines.push("");
  lines.push("## 3. Page Sections");
  for (const s of sectionDefs) {
    lines.push(`- **${s.title}:** ${getOptionLabel(s.options, spec.sections[s.key])}`);
  }
  lines.push("");
  lines.push("---");
  lines.push(`Generated by BuildItToday.ai Design Studio on ${new Date().toISOString()}`);
  return lines.join("\n");
}

export function buildCssVars(spec: DesignSpec): string {
  const c = themes[spec.colorTheme].colors;
  const dc = resolveDarkCanvas(spec);
  const isDark = spec.mode === "dark";
  const bg = isDark ? dc.bg : c.light;
  const fg = isDark ? dc.fg : c.dark;
  const card = isDark ? dc.card : c.lightAlt;
  const border = isDark ? dc.border : c.border;
  const type = resolveType(spec);
  return `:root {
  --background: ${hexToHsl(bg)};
  --foreground: ${hexToHsl(fg)};
  --card: ${hexToHsl(card)};
  --card-foreground: ${hexToHsl(fg)};
  --primary: ${hexToHsl(c.primary)};
  --primary-foreground: 0 0% 100%;
  --secondary: ${hexToHsl(c.light)};
  --secondary-foreground: ${hexToHsl(c.dark)};
  --muted: ${hexToHsl(c.light)};
  --muted-foreground: ${hexToHsl(c.textMuted)};
  --accent: ${hexToHsl(c.primary)};
  --accent-foreground: 0 0% 100%;
  --destructive: 0 84% 60%;
  --destructive-foreground: 0 0% 100%;
  --border: ${hexToHsl(border)};
  --input: ${hexToHsl(border)};
  --ring: ${hexToHsl(c.primary)};
  --radius: ${radiusRem[spec.radius]};
  --font-heading: ${type.headingFont};
  --font-body: ${type.bodyFont};
  --font-heading-weight: ${type.headingWeight};
  --font-heading-style: ${type.headingStyle};
  --font-body-weight: ${type.bodyWeight};
  --font-letter-spacing: ${type.letterSpacing};
  --font-heading-case: ${type.headingCase};
}`;
}

function hexToHsl(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = (g - b) / d + (g < b ? 6 : 0);
    else if (max === g) h = (b - r) / d + 2;
    else h = (r - g) / d + 4;
    h /= 6;
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

export function buildTailwind(spec: DesignSpec): string {
  const c = themes[spec.colorTheme].colors;
  return `module.exports = {
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
    },
  },
};`;
}