import type { MockupConfig } from "@/components/website-mockup";

// Per-business website mockup configurations.
// Each business gets its own brand colors and a distinct mini-site layout
// so the portfolio reads as 8 real, distinct websites — not a repeated template.

export const mockupConfigs: Record<string, MockupConfig> = {
  "Sunny's Hair Salon": {
    name: "Sunny's Hair Salon",
    url: "sunnyshairsalon.com",
    brand: "#C96F4A",
    brandDark: "#8A4A30",
    accent: "#E8D5C4",
    bg: "#FBF6F1",
    layout: "booking",
    tagline: "Book your next look",
  },
  "QuickFix Plumbing": {
    name: "QuickFix Plumbing",
    url: "quickfixplumbing.com",
    brand: "#2F6FB2",
    brandDark: "#1D4E82",
    accent: "#B8C4D0",
    bg: "#F4F7FA",
    layout: "services",
    tagline: "24/7 emergency service",
  },
  "Miami Bites Restaurant": {
    name: "Miami Bites",
    url: "miamibites.com",
    brand: "#C0392B",
    brandDark: "#8E2A20",
    accent: "#D4A574",
    bg: "#FDF6EC",
    layout: "menu",
    tagline: "Taste the flavor",
  },
  "Sparkle Cleaners": {
    name: "Sparkle Cleaners",
    url: "sparklecleaners.com",
    brand: "#4A9E8F",
    brandDark: "#2F6E63",
    accent: "#A8C5A0",
    bg: "#F3F8F6",
    layout: "services",
    tagline: "Fresh & spotless",
  },
  "Dr. Smith Dental": {
    name: "Dr. Smith Dental",
    url: "drsmithdental.com",
    brand: "#5B7DB1",
    brandDark: "#3D5A85",
    accent: "#C5B8D4",
    bg: "#F5F7FB",
    layout: "booking",
    tagline: "Healthy smiles",
  },
  "Sunshine Landscaping": {
    name: "Sunshine Landscaping",
    url: "sunshinelandscaping.com",
    brand: "#5E8C3A",
    brandDark: "#3F6326",
    accent: "#8FA87A",
    bg: "#F4F8F0",
    layout: "gallery",
    tagline: "Beautiful outdoor spaces",
  },
  "Paws Pet Grooming": {
    name: "Paws Pet Grooming",
    url: "pawspetgrooming.com",
    brand: "#B07A4A",
    brandDark: "#7E5430",
    accent: "#D4B896",
    bg: "#FBF6F0",
    layout: "gallery",
    tagline: "Pamper your pet",
  },
  "Elite Auto Repair": {
    name: "Elite Auto Repair",
    url: "eliteautorepair.com",
    brand: "#4A5568",
    brandDark: "#2D3748",
    accent: "#9CA3AF",
    bg: "#F4F5F7",
    layout: "repair",
    tagline: "Expert mechanics",
  },
};